spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 12
      connection-timeout: 60000
      minimum-idle: 10
      idle-timeout: 500000
      max-lifetime: 540000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true